language: ruby
rvm:
  - 2.7.4

services:
  - postgresql

before_install:
  - bundle config set deployment 'true'
  - bundle config --local deployment true
  - bundle install --quiet --jobs 4
  - bundle install --path vendor/cache

before_script:
  - psql -c 'create database db;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

stages:
  - compile
  - test
  - name: deploy
    if: branch = main

jobs:
  include:
    - stage: tests
      script:
        - bundle exec rake spec
        - bundle exec rake cucumber