language: ruby
rvm:
  - 2.7.4

services:
  - postgresql

before_install:
  - gem install bundler

stages:
  - compile
  - test
  - name: deploy
    if: branch = main

before_script:
  - bundle config set deployment 'true'
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

jobs:
  include:
    - stage: tests
      script:
        - bundle exec rake rspec
        - bundle exec rake cucumber