language: ruby
rvm:
  - 2.7.4

services:
  - postgresql

stages:
  - compile
  - test
  - name: deploy
    if: branch = main

before_script:
  - bundle config set deployment 'true'

jobs:
  include:
    - stage: tests
      script:
        - bundle exec rake rspec
        - bundle exec rake cucumber