language: ruby
rvm:
  - 2.7.4

services:
  - postgresql

before_install:
  - bundle config set deployment 'true'

stages:
  - compile
  - test
  - name: deploy
    if: branch = main

jobs:
  include:
    - stage: tests
      script:
        - bundle exec rake rspec
        - bundle exec rake cucumber