default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  database: envsignal_test

