name: Ruby Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: envsignal_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.4
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run tests
      env: 
        DATABASE_URL: postgres://postgres:@localhost:5432/test
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        RAILS_ENV: test
      run: |
        bundle exec rails db:prepare
        bundle exec rake
  coverage:
    steps:
      needs: [ test ]
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CODECLIMATE_COVERAGEKEY}}